name: 刷步数

on:
  schedule:
    - cron: '27 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:        
        #config-name: [CONFIG, CONFIG1, CONFIG2, CONFIG3, CONFIG4, CONFIG5, CONFIG6, CONFIG7, CONFIG8, CONFIG9]
        config-name: [CONFIG0, CONFIG1, CONFIG2] # 假设你有 CONFIG1 和 CONFIG2 这两个 Secrets
    timeout-minutes: 240
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          
      - name: 开始
        env:
            CONFIG: ${{ secrets[matrix.config-name] }} # 使用矩阵策略动态选择 Secret
        run: |
          pip3 install requests pytz
          python3 main.py
